services:
  fledge-dev:
    image: ghcr.io/nus-silicon-designers/fledge-toolchain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      FLEDGE_IN_CONTAINER: "1"
    tty: true
    stdin_open: true
