services:
  fledge-dev:
    image: ghcr.io/nus-silicon-club/fledge-toolchain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
